// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adsimulate.proto

public final class Adsimulate {
  private Adsimulate() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ADValueOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated uint32 uiMainAds = 1;
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    java.util.List<java.lang.Integer> getUiMainAdsList();
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    int getUiMainAdsCount();
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    int getUiMainAds(int index);

    // repeated uint32 uiSubAds = 2;
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    java.util.List<java.lang.Integer> getUiSubAdsList();
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    int getUiSubAdsCount();
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    int getUiSubAds(int index);
  }
  /**
   * Protobuf type {@code ADValue}
   */
  public static final class ADValue extends
      com.google.protobuf.GeneratedMessage
      implements ADValueOrBuilder {
    // Use ADValue.newBuilder() to construct.
    private ADValue(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ADValue(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ADValue defaultInstance;
    public static ADValue getDefaultInstance() {
      return defaultInstance;
    }

    public ADValue getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ADValue(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                uiMainAds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              uiMainAds_.add(input.readUInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                uiMainAds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                uiMainAds_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 16: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                uiSubAds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              uiSubAds_.add(input.readUInt32());
              break;
            }
            case 18: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
                uiSubAds_ = new java.util.ArrayList<java.lang.Integer>();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                uiSubAds_.add(input.readUInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          uiMainAds_ = java.util.Collections.unmodifiableList(uiMainAds_);
        }
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          uiSubAds_ = java.util.Collections.unmodifiableList(uiSubAds_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Adsimulate.internal_static_ADValue_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Adsimulate.internal_static_ADValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Adsimulate.ADValue.class, Adsimulate.ADValue.Builder.class);
    }

    public static com.google.protobuf.Parser<ADValue> PARSER =
        new com.google.protobuf.AbstractParser<ADValue>() {
      public ADValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ADValue(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ADValue> getParserForType() {
      return PARSER;
    }

    // repeated uint32 uiMainAds = 1;
    public static final int UIMAINADS_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> uiMainAds_;
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getUiMainAdsList() {
      return uiMainAds_;
    }
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    public int getUiMainAdsCount() {
      return uiMainAds_.size();
    }
    /**
     * <code>repeated uint32 uiMainAds = 1;</code>
     *
     * <pre>
     *主波
     * </pre>
     */
    public int getUiMainAds(int index) {
      return uiMainAds_.get(index);
    }

    // repeated uint32 uiSubAds = 2;
    public static final int UISUBADS_FIELD_NUMBER = 2;
    private java.util.List<java.lang.Integer> uiSubAds_;
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    public java.util.List<java.lang.Integer>
        getUiSubAdsList() {
      return uiSubAds_;
    }
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    public int getUiSubAdsCount() {
      return uiSubAds_.size();
    }
    /**
     * <code>repeated uint32 uiSubAds = 2;</code>
     *
     * <pre>
     *副波
     * </pre>
     */
    public int getUiSubAds(int index) {
      return uiSubAds_.get(index);
    }

    private void initFields() {
      uiMainAds_ = java.util.Collections.emptyList();
      uiSubAds_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < uiMainAds_.size(); i++) {
        output.writeUInt32(1, uiMainAds_.get(i));
      }
      for (int i = 0; i < uiSubAds_.size(); i++) {
        output.writeUInt32(2, uiSubAds_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < uiMainAds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(uiMainAds_.get(i));
        }
        size += dataSize;
        size += 1 * getUiMainAdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < uiSubAds_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(uiSubAds_.get(i));
        }
        size += dataSize;
        size += 1 * getUiSubAdsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Adsimulate.ADValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Adsimulate.ADValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Adsimulate.ADValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Adsimulate.ADValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Adsimulate.ADValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Adsimulate.ADValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Adsimulate.ADValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Adsimulate.ADValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Adsimulate.ADValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Adsimulate.ADValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Adsimulate.ADValue prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ADValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Adsimulate.ADValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Adsimulate.internal_static_ADValue_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Adsimulate.internal_static_ADValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Adsimulate.ADValue.class, Adsimulate.ADValue.Builder.class);
      }

      // Construct using Adsimulate.ADValue.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        uiMainAds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        uiSubAds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Adsimulate.internal_static_ADValue_descriptor;
      }

      public Adsimulate.ADValue getDefaultInstanceForType() {
        return Adsimulate.ADValue.getDefaultInstance();
      }

      public Adsimulate.ADValue build() {
        Adsimulate.ADValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Adsimulate.ADValue buildPartial() {
        Adsimulate.ADValue result = new Adsimulate.ADValue(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uiMainAds_ = java.util.Collections.unmodifiableList(uiMainAds_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uiMainAds_ = uiMainAds_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          uiSubAds_ = java.util.Collections.unmodifiableList(uiSubAds_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.uiSubAds_ = uiSubAds_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Adsimulate.ADValue) {
          return mergeFrom((Adsimulate.ADValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Adsimulate.ADValue other) {
        if (other == Adsimulate.ADValue.getDefaultInstance()) return this;
        if (!other.uiMainAds_.isEmpty()) {
          if (uiMainAds_.isEmpty()) {
            uiMainAds_ = other.uiMainAds_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUiMainAdsIsMutable();
            uiMainAds_.addAll(other.uiMainAds_);
          }
          onChanged();
        }
        if (!other.uiSubAds_.isEmpty()) {
          if (uiSubAds_.isEmpty()) {
            uiSubAds_ = other.uiSubAds_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureUiSubAdsIsMutable();
            uiSubAds_.addAll(other.uiSubAds_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Adsimulate.ADValue parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Adsimulate.ADValue) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated uint32 uiMainAds = 1;
      private java.util.List<java.lang.Integer> uiMainAds_ = java.util.Collections.emptyList();
      private void ensureUiMainAdsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          uiMainAds_ = new java.util.ArrayList<java.lang.Integer>(uiMainAds_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getUiMainAdsList() {
        return java.util.Collections.unmodifiableList(uiMainAds_);
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public int getUiMainAdsCount() {
        return uiMainAds_.size();
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public int getUiMainAds(int index) {
        return uiMainAds_.get(index);
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public Builder setUiMainAds(
          int index, int value) {
        ensureUiMainAdsIsMutable();
        uiMainAds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public Builder addUiMainAds(int value) {
        ensureUiMainAdsIsMutable();
        uiMainAds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public Builder addAllUiMainAds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUiMainAdsIsMutable();
        super.addAll(values, uiMainAds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiMainAds = 1;</code>
       *
       * <pre>
       *主波
       * </pre>
       */
      public Builder clearUiMainAds() {
        uiMainAds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // repeated uint32 uiSubAds = 2;
      private java.util.List<java.lang.Integer> uiSubAds_ = java.util.Collections.emptyList();
      private void ensureUiSubAdsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          uiSubAds_ = new java.util.ArrayList<java.lang.Integer>(uiSubAds_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public java.util.List<java.lang.Integer>
          getUiSubAdsList() {
        return java.util.Collections.unmodifiableList(uiSubAds_);
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public int getUiSubAdsCount() {
        return uiSubAds_.size();
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public int getUiSubAds(int index) {
        return uiSubAds_.get(index);
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public Builder setUiSubAds(
          int index, int value) {
        ensureUiSubAdsIsMutable();
        uiSubAds_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public Builder addUiSubAds(int value) {
        ensureUiSubAdsIsMutable();
        uiSubAds_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public Builder addAllUiSubAds(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureUiSubAdsIsMutable();
        super.addAll(values, uiSubAds_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint32 uiSubAds = 2;</code>
       *
       * <pre>
       *副波
       * </pre>
       */
      public Builder clearUiSubAds() {
        uiSubAds_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:ADValue)
    }

    static {
      defaultInstance = new ADValue(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ADValue)
  }

  public interface ADSimulateOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .ADValue data = 1;
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    java.util.List<Adsimulate.ADValue> 
        getDataList();
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    Adsimulate.ADValue getData(int index);
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    int getDataCount();
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    java.util.List<? extends Adsimulate.ADValueOrBuilder> 
        getDataOrBuilderList();
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    Adsimulate.ADValueOrBuilder getDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code ADSimulate}
   */
  public static final class ADSimulate extends
      com.google.protobuf.GeneratedMessage
      implements ADSimulateOrBuilder {
    // Use ADSimulate.newBuilder() to construct.
    private ADSimulate(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ADSimulate(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ADSimulate defaultInstance;
    public static ADSimulate getDefaultInstance() {
      return defaultInstance;
    }

    public ADSimulate getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ADSimulate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                data_ = new java.util.ArrayList<Adsimulate.ADValue>();
                mutable_bitField0_ |= 0x00000001;
              }
              data_.add(input.readMessage(Adsimulate.ADValue.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = java.util.Collections.unmodifiableList(data_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Adsimulate.internal_static_ADSimulate_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Adsimulate.internal_static_ADSimulate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Adsimulate.ADSimulate.class, Adsimulate.ADSimulate.Builder.class);
    }

    public static com.google.protobuf.Parser<ADSimulate> PARSER =
        new com.google.protobuf.AbstractParser<ADSimulate>() {
      public ADSimulate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ADSimulate(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ADSimulate> getParserForType() {
      return PARSER;
    }

    // repeated .ADValue data = 1;
    public static final int DATA_FIELD_NUMBER = 1;
    private java.util.List<Adsimulate.ADValue> data_;
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    public java.util.List<Adsimulate.ADValue> getDataList() {
      return data_;
    }
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    public java.util.List<? extends Adsimulate.ADValueOrBuilder> 
        getDataOrBuilderList() {
      return data_;
    }
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    public int getDataCount() {
      return data_.size();
    }
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    public Adsimulate.ADValue getData(int index) {
      return data_.get(index);
    }
    /**
     * <code>repeated .ADValue data = 1;</code>
     */
    public Adsimulate.ADValueOrBuilder getDataOrBuilder(
        int index) {
      return data_.get(index);
    }

    private void initFields() {
      data_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < data_.size(); i++) {
        output.writeMessage(1, data_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < data_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, data_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Adsimulate.ADSimulate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Adsimulate.ADSimulate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Adsimulate.ADSimulate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Adsimulate.ADSimulate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Adsimulate.ADSimulate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Adsimulate.ADSimulate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Adsimulate.ADSimulate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Adsimulate.ADSimulate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Adsimulate.ADSimulate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Adsimulate.ADSimulate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Adsimulate.ADSimulate prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ADSimulate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements Adsimulate.ADSimulateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Adsimulate.internal_static_ADSimulate_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Adsimulate.internal_static_ADSimulate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Adsimulate.ADSimulate.class, Adsimulate.ADSimulate.Builder.class);
      }

      // Construct using Adsimulate.ADSimulate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDataFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Adsimulate.internal_static_ADSimulate_descriptor;
      }

      public Adsimulate.ADSimulate getDefaultInstanceForType() {
        return Adsimulate.ADSimulate.getDefaultInstance();
      }

      public Adsimulate.ADSimulate build() {
        Adsimulate.ADSimulate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Adsimulate.ADSimulate buildPartial() {
        Adsimulate.ADSimulate result = new Adsimulate.ADSimulate(this);
        int from_bitField0_ = bitField0_;
        if (dataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            data_ = java.util.Collections.unmodifiableList(data_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.data_ = data_;
        } else {
          result.data_ = dataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Adsimulate.ADSimulate) {
          return mergeFrom((Adsimulate.ADSimulate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Adsimulate.ADSimulate other) {
        if (other == Adsimulate.ADSimulate.getDefaultInstance()) return this;
        if (dataBuilder_ == null) {
          if (!other.data_.isEmpty()) {
            if (data_.isEmpty()) {
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataIsMutable();
              data_.addAll(other.data_);
            }
            onChanged();
          }
        } else {
          if (!other.data_.isEmpty()) {
            if (dataBuilder_.isEmpty()) {
              dataBuilder_.dispose();
              dataBuilder_ = null;
              data_ = other.data_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getDataFieldBuilder() : null;
            } else {
              dataBuilder_.addAllMessages(other.data_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Adsimulate.ADSimulate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Adsimulate.ADSimulate) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .ADValue data = 1;
      private java.util.List<Adsimulate.ADValue> data_ =
        java.util.Collections.emptyList();
      private void ensureDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          data_ = new java.util.ArrayList<Adsimulate.ADValue>(data_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          Adsimulate.ADValue, Adsimulate.ADValue.Builder, Adsimulate.ADValueOrBuilder> dataBuilder_;

      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public java.util.List<Adsimulate.ADValue> getDataList() {
        if (dataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(data_);
        } else {
          return dataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public int getDataCount() {
        if (dataBuilder_ == null) {
          return data_.size();
        } else {
          return dataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Adsimulate.ADValue getData(int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);
        } else {
          return dataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder setData(
          int index, Adsimulate.ADValue value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.set(index, value);
          onChanged();
        } else {
          dataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder setData(
          int index, Adsimulate.ADValue.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder addData(Adsimulate.ADValue value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(value);
          onChanged();
        } else {
          dataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder addData(
          int index, Adsimulate.ADValue value) {
        if (dataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataIsMutable();
          data_.add(index, value);
          onChanged();
        } else {
          dataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder addData(
          Adsimulate.ADValue.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder addData(
          int index, Adsimulate.ADValue.Builder builderForValue) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder addAllData(
          java.lang.Iterable<? extends Adsimulate.ADValue> values) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          super.addAll(values, data_);
          onChanged();
        } else {
          dataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder clearData() {
        if (dataBuilder_ == null) {
          data_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Builder removeData(int index) {
        if (dataBuilder_ == null) {
          ensureDataIsMutable();
          data_.remove(index);
          onChanged();
        } else {
          dataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Adsimulate.ADValue.Builder getDataBuilder(
          int index) {
        return getDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Adsimulate.ADValueOrBuilder getDataOrBuilder(
          int index) {
        if (dataBuilder_ == null) {
          return data_.get(index);  } else {
          return dataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public java.util.List<? extends Adsimulate.ADValueOrBuilder> 
           getDataOrBuilderList() {
        if (dataBuilder_ != null) {
          return dataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(data_);
        }
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Adsimulate.ADValue.Builder addDataBuilder() {
        return getDataFieldBuilder().addBuilder(
            Adsimulate.ADValue.getDefaultInstance());
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public Adsimulate.ADValue.Builder addDataBuilder(
          int index) {
        return getDataFieldBuilder().addBuilder(
            index, Adsimulate.ADValue.getDefaultInstance());
      }
      /**
       * <code>repeated .ADValue data = 1;</code>
       */
      public java.util.List<Adsimulate.ADValue.Builder> 
           getDataBuilderList() {
        return getDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Adsimulate.ADValue, Adsimulate.ADValue.Builder, Adsimulate.ADValueOrBuilder> 
          getDataFieldBuilder() {
        if (dataBuilder_ == null) {
          dataBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Adsimulate.ADValue, Adsimulate.ADValue.Builder, Adsimulate.ADValueOrBuilder>(
                  data_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          data_ = null;
        }
        return dataBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:ADSimulate)
    }

    static {
      defaultInstance = new ADSimulate(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:ADSimulate)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ADValue_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ADValue_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ADSimulate_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ADSimulate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020adsimulate.proto\".\n\007ADValue\022\021\n\tuiMainA" +
      "ds\030\001 \003(\r\022\020\n\010uiSubAds\030\002 \003(\r\"$\n\nADSimulate" +
      "\022\026\n\004data\030\001 \003(\0132\010.ADValue"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ADValue_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ADValue_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ADValue_descriptor,
              new java.lang.String[] { "UiMainAds", "UiSubAds", });
          internal_static_ADSimulate_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_ADSimulate_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ADSimulate_descriptor,
              new java.lang.String[] { "Data", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
