// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adsimulate.proto

#ifndef PROTOBUF_adsimulate_2eproto__INCLUDED
#define PROTOBUF_adsimulate_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_adsimulate_2eproto();
void protobuf_AssignDesc_adsimulate_2eproto();
void protobuf_ShutdownFile_adsimulate_2eproto();

class ADValue;
class ADSimulate;

// ===================================================================

class ADValue : public ::google::protobuf::Message {
 public:
  ADValue();
  virtual ~ADValue();

  ADValue(const ADValue& from);

  inline ADValue& operator=(const ADValue& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ADValue& default_instance();

  void Swap(ADValue* other);

  // implements Message ----------------------------------------------

  ADValue* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ADValue& from);
  void MergeFrom(const ADValue& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated uint32 uiMainAds = 1;
  inline int uimainads_size() const;
  inline void clear_uimainads();
  static const int kUiMainAdsFieldNumber = 1;
  inline ::google::protobuf::uint32 uimainads(int index) const;
  inline void set_uimainads(int index, ::google::protobuf::uint32 value);
  inline void add_uimainads(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      uimainads() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_uimainads();

  // repeated uint32 uiSubAds = 2;
  inline int uisubads_size() const;
  inline void clear_uisubads();
  static const int kUiSubAdsFieldNumber = 2;
  inline ::google::protobuf::uint32 uisubads(int index) const;
  inline void set_uisubads(int index, ::google::protobuf::uint32 value);
  inline void add_uisubads(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      uisubads() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_uisubads();

  // @@protoc_insertion_point(class_scope:ADValue)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > uimainads_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > uisubads_;
  friend void  protobuf_AddDesc_adsimulate_2eproto();
  friend void protobuf_AssignDesc_adsimulate_2eproto();
  friend void protobuf_ShutdownFile_adsimulate_2eproto();

  void InitAsDefaultInstance();
  static ADValue* default_instance_;
};
// -------------------------------------------------------------------

class ADSimulate : public ::google::protobuf::Message {
 public:
  ADSimulate();
  virtual ~ADSimulate();

  ADSimulate(const ADSimulate& from);

  inline ADSimulate& operator=(const ADSimulate& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ADSimulate& default_instance();

  void Swap(ADSimulate* other);

  // implements Message ----------------------------------------------

  ADSimulate* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ADSimulate& from);
  void MergeFrom(const ADSimulate& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .ADValue data = 1;
  inline int data_size() const;
  inline void clear_data();
  static const int kDataFieldNumber = 1;
  inline const ::ADValue& data(int index) const;
  inline ::ADValue* mutable_data(int index);
  inline ::ADValue* add_data();
  inline const ::google::protobuf::RepeatedPtrField< ::ADValue >&
      data() const;
  inline ::google::protobuf::RepeatedPtrField< ::ADValue >*
      mutable_data();

  // @@protoc_insertion_point(class_scope:ADSimulate)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::ADValue > data_;
  friend void  protobuf_AddDesc_adsimulate_2eproto();
  friend void protobuf_AssignDesc_adsimulate_2eproto();
  friend void protobuf_ShutdownFile_adsimulate_2eproto();

  void InitAsDefaultInstance();
  static ADSimulate* default_instance_;
};
// ===================================================================


// ===================================================================

// ADValue

// repeated uint32 uiMainAds = 1;
inline int ADValue::uimainads_size() const {
  return uimainads_.size();
}
inline void ADValue::clear_uimainads() {
  uimainads_.Clear();
}
inline ::google::protobuf::uint32 ADValue::uimainads(int index) const {
  // @@protoc_insertion_point(field_get:ADValue.uiMainAds)
  return uimainads_.Get(index);
}
inline void ADValue::set_uimainads(int index, ::google::protobuf::uint32 value) {
  uimainads_.Set(index, value);
  // @@protoc_insertion_point(field_set:ADValue.uiMainAds)
}
inline void ADValue::add_uimainads(::google::protobuf::uint32 value) {
  uimainads_.Add(value);
  // @@protoc_insertion_point(field_add:ADValue.uiMainAds)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ADValue::uimainads() const {
  // @@protoc_insertion_point(field_list:ADValue.uiMainAds)
  return uimainads_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ADValue::mutable_uimainads() {
  // @@protoc_insertion_point(field_mutable_list:ADValue.uiMainAds)
  return &uimainads_;
}

// repeated uint32 uiSubAds = 2;
inline int ADValue::uisubads_size() const {
  return uisubads_.size();
}
inline void ADValue::clear_uisubads() {
  uisubads_.Clear();
}
inline ::google::protobuf::uint32 ADValue::uisubads(int index) const {
  // @@protoc_insertion_point(field_get:ADValue.uiSubAds)
  return uisubads_.Get(index);
}
inline void ADValue::set_uisubads(int index, ::google::protobuf::uint32 value) {
  uisubads_.Set(index, value);
  // @@protoc_insertion_point(field_set:ADValue.uiSubAds)
}
inline void ADValue::add_uisubads(::google::protobuf::uint32 value) {
  uisubads_.Add(value);
  // @@protoc_insertion_point(field_add:ADValue.uiSubAds)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
ADValue::uisubads() const {
  // @@protoc_insertion_point(field_list:ADValue.uiSubAds)
  return uisubads_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
ADValue::mutable_uisubads() {
  // @@protoc_insertion_point(field_mutable_list:ADValue.uiSubAds)
  return &uisubads_;
}

// -------------------------------------------------------------------

// ADSimulate

// repeated .ADValue data = 1;
inline int ADSimulate::data_size() const {
  return data_.size();
}
inline void ADSimulate::clear_data() {
  data_.Clear();
}
inline const ::ADValue& ADSimulate::data(int index) const {
  // @@protoc_insertion_point(field_get:ADSimulate.data)
  return data_.Get(index);
}
inline ::ADValue* ADSimulate::mutable_data(int index) {
  // @@protoc_insertion_point(field_mutable:ADSimulate.data)
  return data_.Mutable(index);
}
inline ::ADValue* ADSimulate::add_data() {
  // @@protoc_insertion_point(field_add:ADSimulate.data)
  return data_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ADValue >&
ADSimulate::data() const {
  // @@protoc_insertion_point(field_list:ADSimulate.data)
  return data_;
}
inline ::google::protobuf::RepeatedPtrField< ::ADValue >*
ADSimulate::mutable_data() {
  // @@protoc_insertion_point(field_mutable_list:ADSimulate.data)
  return &data_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_adsimulate_2eproto__INCLUDED
